// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package sqlCode

import (
	"database/sql"
)

type Container struct {
	ID            int64
	Name          string
	Volume        int64
	UnitOfMeasure int64
}

type Ingredient struct {
	ID       int64
	Name     string
	Abv      sql.NullFloat64
	Category int64
}

type IngredientCategory struct {
	ID             int64
	Name           string
	ParentCategory sql.NullInt64
}

type InventoryItem struct {
	ID            int64
	Content       int64
	Container     int64
	CurrentVolume int64
	UnitOfMeasure int64
}

type Metadatum struct {
	ID           int64
	MajorVersion int64
	MinorVersion int64
	PatchVersion int64
	DbVersion    int64
}

type Recipe struct {
	ID          int64
	Name        string
	Rating      sql.NullInt64
	DateCreated sql.NullString
}

type RecipeItem struct {
	ID        int64
	RecipeTag int64
	Content   int64
	Container sql.NullInt64
}

type UnitOfMeasure struct {
	ID   int64
	Name string
}
